"""
Antigravity Artifact System — Structured code blueprints for project spaces.

Artifacts are JSON files stored in /projects/[name]/orchestration/artifacts/.
Each artifact is a reviewable, immutable code blueprint generated by Tier 2.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional, Union


ARTIFACT_TYPES = [
    "directory_structure",
    "database_schema",
    "source_block",
    "dependency_list",
    "implementation_plan",
    "test_plan",
    "api_spec",
]


@dataclass
class Artifact:
    """A single Antigravity Artifact (immutable code blueprint)."""
    artifact_type: str
    name: str
    description: str
    content: dict
    project_space: str
    version: str = "1.0"
    generated_by: str = "tier_2_gemini"
    metadata: dict = None

    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}

    @property
    def filename(self) -> str:
        safe_name = self.name.lower().replace(" ", "_").replace("-", "_")
        return f"{self.artifact_type}_{safe_name}.json"

    @property
    def filepath(self) -> str:
        return str(
            Path(self.project_space) / "orchestration" / "artifacts" / self.filename
        )

    def save(self) -> str:
        """Save artifact to disk. Returns the file path."""
        path = Path(self.filepath)
        path.parent.mkdir(parents=True, exist_ok=True)

        data = {
            "artifact_type": self.artifact_type,
            "name": self.name,
            "description": self.description,
            "content": self.content,
            "version": self.version,
            "generated_by": self.generated_by,
            "generated_at": datetime.now().isoformat(),
            "metadata": self.metadata,
        }

        path.write_text(json.dumps(data, indent=2))
        return str(path)

    def to_dict(self) -> dict:
        return {
            "artifact_type": self.artifact_type,
            "name": self.name,
            "description": self.description,
            "content": self.content,
            "version": self.version,
            "generated_by": self.generated_by,
            "generated_at": datetime.now().isoformat(),
            "metadata": self.metadata,
        }


def list_artifacts(project_space: str) -> list[dict]:
    """List all artifacts in a project."""
    artifact_dir = Path(project_space) / "orchestration" / "artifacts"
    if not artifact_dir.exists():
        return []

    artifacts = []
    for f in sorted(artifact_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text())
            artifacts.append({
                "filename": f.name,
                "type": data.get("artifact_type", "unknown"),
                "name": data.get("name", ""),
                "version": data.get("version", ""),
                "generated_at": data.get("generated_at", ""),
            })
        except Exception:
            pass

    return artifacts


def get_artifact(project_space: str, artifact_type: str, name: str) -> dict | None:
    """Get a specific artifact by type and name."""
    artifact_dir = Path(project_space) / "orchestration" / "artifacts"
    if not artifact_dir.exists():
        return None

    for f in artifact_dir.glob(f"{artifact_type}_*.json"):
        try:
            data = json.loads(f.read_text())
            if data.get("name", "").lower().replace(" ", "_") == name.lower().replace(" ", "_"):
                return data
        except Exception:
            pass

    return None


def create_directory_artifact(project_space: str, structure: dict,
                              name: str = "Project Layout") -> Artifact:
    """Create a directory structure artifact."""
    return Artifact(
        artifact_type="directory_structure",
        name=name,
        description="Complete directory and file layout",
        content={"structure": structure},
        project_space=project_space,
    )


def create_database_schema_artifact(project_space: str, tables: list[dict],
                                   indexes: list[dict] = None,
                                   name: str = "Database Schema") -> Artifact:
    """Create a database schema artifact."""
    return Artifact(
        artifact_type="database_schema",
        name=name,
        description="Table definitions, relationships, and indexes",
        content={"tables": tables, "indexes": indexes or []},
        project_space=project_space,
    )


def create_implementation_plan_artifact(project_space: str,
                                         endpoints: list[dict],
                                         implementation_order: list[str],
                                         name: str = "Implementation Plan") -> Artifact:
    """Create an API implementation plan artifact."""
    return Artifact(
        artifact_type="implementation_plan",
        name=name,
        description="API endpoint definitions and implementation sequence",
        content={
            "endpoints": endpoints,
            "implementation_order": implementation_order,
        },
        project_space=project_space,
    )


def create_source_block_artifact(project_space: str, file_path: str,
                                  code: str, description: str = "",
                                  name: str = "") -> Artifact:
    """Create a source code block artifact."""
    return Artifact(
        artifact_type="source_block",
        name=name or f"Source: {file_path}",
        description=description or f"Source code for {file_path}",
        content={"file_path": file_path, "code": code},
        project_space=project_space,
    )


def create_dependency_list_artifact(project_space: str,
                                    dependencies: list[dict],
                                    name: str = "Dependencies") -> Artifact:
    """Create a dependency list artifact."""
    return Artifact(
        artifact_type="dependency_list",
        name=name,
        description="Project dependencies and versions",
        content={"dependencies": dependencies},
        project_space=project_space,
    )
