#!/usr/bin/env python3
"""
MoiraiCore — Feedback Loop Script
Layer 7 of the Agent Operating System

Scans the workspace for new files, generates memory entries,
and writes them back into the memory vault.

Usage:
    python3 feedback-loop.py           # Run once
    python3 feedback-loop.py --watch   # Watch continuously
    python3 feedback-loop.py --summary # Print summary only
"""

import os
import sys
import json
import hashlib
from datetime import datetime, timezone
from pathlib import Path

# ─── Config ───
AGENT_OS_ROOT = Path(__file__).parent.parent
if not (AGENT_OS_ROOT / "memory-vault").exists():
    AGENT_OS_ROOT = Path(os.environ.get("AGENT_OS_ROOT", str(Path(__file__).resolve().parents[1])))

WORKSPACE = AGENT_OS_ROOT / "workspace"
VAULT = AGENT_OS_ROOT / "memory-vault"
LOOP_DIR = VAULT / "loop"
DAILY_DIR = VAULT / "daily"
CONTEXT_DIR = VAULT / "context"
INDEX_FILE = LOOP_DIR / ".index.json"

# File type → folder mapping
TYPE_MAP = {
    ".png": "images", ".jpg": "images", ".jpeg": "images", ".gif": "images",
    ".webp": "images", ".svg": "images", ".bmp": "images", ".ico": "images",
    ".mp4": "videos", ".mov": "videos", ".avi": "videos", ".webm": "videos",
    ".mkv": "videos",
    ".mp3": "audio", ".wav": "audio", ".ogg": "audio", ".m4a": "audio",
    ".flac": "audio",
    ".md": "text", ".txt": "text", ".pdf": "text", ".doc": "text",
    ".docx": "text", ".rtf": "text",
    ".py": "code", ".js": "code", ".ts": "code", ".sh": "code",
    ".bash": "code", ".yaml": "code", ".yml": "code", ".json": "code",
    ".toml": "code", ".html": "code", ".css": "code",
}
TYPE_ICONS = {
    "images": "🖼", "videos": "🎬", "audio": "🔊",
    "text": "📄", "code": "💻", "research": "🔍", "unknown": "📁"
}


def file_type(path: Path) -> str:
    """Determine the workspace type for a file."""
    ext = path.suffix.lower()
    return TYPE_MAP.get(ext, "unknown")


def detect_agent(filename: str) -> str:
    """Try to detect which agent created a file from its name."""
    parts = filename.replace("-", "_").replace(" ", "_").split("_")
    known_agents = ["hermes", "claude", "codex", "openclaw", "anti_gravity",
                    "antigravity", "gemini", "chatgpt", "studio"]
    for part in parts:
        if part.lower() in known_agents:
            return part.lower()
    return "unknown"


def extract_date(filename: str) -> str:
    """Extract YYYY-MM-DD from filename if present, else use mtime."""
    import re
    m = re.match(r"(\d{4}-\d{2}-\d{2})", filename)
    if m:
        return m.group(1)
    return None


def scan_workspace() -> list[dict]:
    """Scan all workspace files and return metadata."""
    files = []
    for sub in WORKSPACE.iterdir():
        if sub.is_file() and sub.name.startswith("."):
            continue
        if sub.is_dir():
            for f in sub.rglob("*"):
                if f.is_file() and not f.name.startswith("."):
                    files.append(_file_meta(f))
        elif sub.is_file() and not sub.name.startswith("."):
            files.append(_file_meta(sub))
    return files


def _file_meta(path: Path) -> dict:
    stat = path.stat()
    name = path.name
    ftype = file_type(path)
    agent = detect_agent(name)
    date = extract_date(name) or datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d")
    
    # Compute hash for change detection
    content_hash = hashlib.md5(path.read_bytes()).hexdigest()
    
    return {
        "name": name,
        "path": str(path.relative_to(WORKSPACE)),
        "abs_path": str(path),
        "type": ftype,
        "agent": agent,
        "date": date,
        "size": stat.st_size,
        "hash": content_hash,
        "mtime": stat.st_mtime,
    }


def load_index() -> dict:
    """Load the index of previously indexed files."""
    if INDEX_FILE.exists():
        return json.loads(INDEX_FILE.read_text())
    return {"files": {}, "runs": 0, "last_run": None}


def save_index(index: dict):
    INDEX_FILE.write_text(json.dumps(index, indent=2))


def generate_daily_note(files: list[dict], new_files: list[dict], date: str) -> str:
    """Generate or update a daily note."""
    daily_file = DAILY_DIR / f"{date}.md"
    
    # Group by type
    by_type = {}
    for f in files:
        by_type.setdefault(f["type"], []).append(f)
    
    by_agent = {}
    for f in files:
        by_agent.setdefault(f["agent"], []).append(f)
    
    lines = [
        f"# 📅 {date} — MoiraiCore Daily Note",
        "",
        f"*Auto-generated by feedback loop. {len(files)} total workspace files, {len(new_files)} new.*",
        "",
        "## Summary",
        ""
    ]
    
    for t, items in sorted(by_type.items()):
        icon = TYPE_ICONS.get(t, "📁")
        lines.append(f"- {icon} **{t.capitalize()}**: {len(items)} files")
    
    lines.append("")
    lines.append("## By Agent")
    lines.append("")
    for agent, items in sorted(by_agent.items()):
        lines.append(f"- **{agent}**: {len(items)} files")
    
    if new_files:
        lines.append("")
        lines.append("## New Files")
        lines.append("")
        for f in new_files:
            icon = TYPE_ICONS.get(f["type"], "📁")
            lines.append(f"- {icon} `{f['path']}` ({f['agent']}, {format_size(f['size'])})")
    
    content = "\n".join(lines) + "\n"
    
    # Merge with existing daily note if present
    if daily_file.exists():
        existing = daily_file.read_text()
        # Append new section
        if "## New Files" not in existing:
            content = existing.rstrip() + "\n\n" + "\n".join(lines[lines.index("## New Files"):])
    
    daily_file.write_text(content)
    return str(daily_file)


def generate_loop_entry(new_files: list[dict], all_files: list[dict], run_number: int):
    """Generate a loop entry documenting this run."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    entry_file = LOOP_DIR / f"run-{run_number:04d}.md"
    
    lines = [
        f"# 🔄 Loop Run #{run_number}",
        "",
        f"**Time:** {now}",
        f"**New files indexed:** {len(new_files)}",
        f"**Total workspace files:** {len(all_files)}",
        ""
    ]
    
    if new_files:
        lines.append("## New Files Indexed")
        lines.append("")
        for f in new_files:
            lines.append(f"- `{f['path']}` → type: {f['type']}, agent: {f['agent']}, size: {format_size(f['size'])}")
    else:
        lines.append("*No new files since last run.*")
    
    entry_file.write_text("\n".join(lines) + "\n")
    return str(entry_file)


def format_size(size: int) -> str:
    if size < 1024:
        return f"{size}B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.1f}KB"
    else:
        return f"{size / (1024 * 1024):.1f}MB"


def run_loop(dry_run: bool = False) -> dict:
    """Execute one feedback loop cycle."""
    # Ensure directories exist
    LOOP_DIR.mkdir(parents=True, exist_ok=True)
    DAILY_DIR.mkdir(parents=True, exist_ok=True)
    CONTEXT_DIR.mkdir(parents=True, exist_ok=True)
    
    index = load_index()
    existing_hashes = {fh for fh in index.get("files", {}).keys() if isinstance(fh, str) and len(fh) == 32}
    
    all_files = scan_workspace()
    new_files = [f for f in all_files if f["hash"] not in existing_hashes]
    
    today = datetime.now().strftime("%Y-%m-%d")
    
    print(f"🔄 MoiraiCore Feedback Loop")
    print(f"{'─' * 40}")
    print(f"  Total workspace files: {len(all_files)}")
    print(f"  New files: {len(new_files)}")
    
    if dry_run:
        if new_files:
            print(f"\nNew files (would be indexed):")
            for f in new_files:
                icon = TYPE_ICONS.get(f["type"], "📁")
                print(f"  {icon} {f['path']}")
        return {"new": len(new_files), "total": len(all_files)}
    
    # Run number
    run_number = index.get("runs", 0) + 1
    
    # Generate outputs
    if all_files:
        daily_note = generate_daily_note(all_files, new_files, today)
        print(f"  📅 Daily note: {daily_note}")
    
    if new_files:
        loop_entry = generate_loop_entry(new_files, all_files, run_number)
        print(f"  📝 Loop entry: {loop_entry}")
    
    # Update index
    for f in new_files:
        index["files"][f["hash"]] = {
            "path": f["path"],
            "type": f["type"],
            "agent": f["agent"],
            "date": f["date"],
            "size": f["size"],
        }
    index["runs"] = run_number
    index["last_run"] = datetime.now().isoformat()
    save_index(index)
    
    print(f"\n✅ Loop run #{run_number} complete.")
    print(f"   Indexed {len(new_files)} new files into memory vault.")
    print(f"   Total tracked: {len(index['files'])}")
    
    return {"new": len(new_files), "total": len(all_files), "run": run_number}


def print_summary():
    """Print a summary of the current state."""
    all_files = scan_workspace()
    
    by_type = {}
    by_agent = {}
    for f in all_files:
        by_type.setdefault(f["type"], []).append(f)
        by_agent.setdefault(f["agent"], []).append(f)
    
    print(f"\n{'═' * 40}")
    print(f"  MoiraiCore — Workspace Summary")
    print(f"{'═' * 40}")
    print(f"\n  Total files: {len(all_files)}")
    
    print(f"\n  By Type:")
    for t, items in sorted(by_type.items()):
        icon = TYPE_ICONS.get(t, "📁")
        total_size = sum(i["size"] for i in items)
        print(f"    {icon} {t:10s} {len(items):3d} files  ({format_size(total_size)})")
    
    print(f"\n  By Agent:")
    for agent, items in sorted(by_agent.items()):
        print(f"    {agent:15s} {len(items):3d} files")
    print()


if __name__ == "__main__":
    if "--summary" in sys.argv:
        print_summary()
    elif "--watch" in sys.argv:
        import time
        print("👁 Watching workspace for changes (Ctrl+C to stop)...")
        while True:
            try:
                result = run_loop()
                if result["new"] > 0:
                    print(f"\n⏰ {datetime.now().strftime('%H:%M:%S')} — {result['new']} new files indexed")
                time.sleep(30)
            except KeyboardInterrupt:
                print("\n👋 Stopped.")
                break
    else:
        run_loop()
