#!/usr/bin/env python3
"""
report_to_pdf.py — Convert a MoiraiCore threat-assessment Markdown report to a
styled PDF using reportlab (platypus).

Supports the subset of Markdown the threat reports use:
  # / ## / ### headings
  | a | b | tables (with leading/trailing pipes tolerated)
  - / * bullet lines
  **bold** spans
  plain paragraphs
  horizontal rule (---)
  *Generated by ...* trailing italic line

Diagrams can be embedded via --image "Title:/path.png" (repeatable); they are
placed in an "Appendix: Diagrams" section, scaled to fit the page width.

Usage:
  python3 report_to_pdf.py <input.md> <output.pdf> [--title "..."] [--image "Title:/path.png"]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, ListFlowable, ListItem,
    Image as RLImage, PageBreak,
)

# ── Palette (matches MoiraiCore dark/alert semantics) ──
INK = colors.HexColor("#1e1e1e")
MUTED = colors.HexColor("#555555")
ACCENT = colors.HexColor("#9E2B25")   # MoiraiCore secondary
HEADER_BG = colors.HexColor("#1B4D3E")  # MoiraiCore primary
ROW_ALT = colors.HexColor("#f2f4f3")
CRIT = colors.HexColor("#ffc9c9")
HIGH = colors.HexColor("#ffd8a8")
MOD = colors.HexColor("#fff3bf")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("H1", parent=ss["Heading1"], textColor=HEADER_BG, fontSize=18,
                          spaceBefore=10, spaceAfter=8))
    ss.add(ParagraphStyle("H2", parent=ss["Heading2"], textColor=ACCENT, fontSize=13,
                          spaceBefore=10, spaceAfter=5))
    ss.add(ParagraphStyle("H3", parent=ss["Heading3"], textColor=INK, fontSize=11,
                          spaceBefore=6, spaceAfter=3))
    ss.add(ParagraphStyle("Body", parent=ss["BodyText"], textColor=INK, fontSize=9.5,
                          leading=13, spaceAfter=4))
    ss.add(ParagraphStyle("Cell", parent=ss["BodyText"], textColor=INK, fontSize=8.5, leading=11))
    ss.add(ParagraphStyle("CellH", parent=ss["BodyText"], textColor=colors.white, fontSize=8.5,
                          leading=11, fontName="Helvetica-Bold"))
    ss.add(ParagraphStyle("Meta", parent=ss["BodyText"], textColor=MUTED, fontSize=8, leading=11))
    ss.add(ParagraphStyle("FigCap", parent=ss["BodyText"], textColor=MUTED, fontSize=8.5,
                          leading=11, spaceBefore=2, spaceAfter=8, alignment=1))
    return ss


def _inline(text: str) -> str:
    """Escape & apply **bold** to reportlab-ready markup."""
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    return text


def _row_level_bg(row_text: str):
    t = row_text.lower()
    if "critical" in t:
        return CRIT
    if "high" in t:
        return HIGH
    if "moderate" in t:
        return MOD
    return None


def md_to_flowables(md: str, styles, title=None):
    flow = []
    lines = md.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        # skip the auto-generated trailing italic line (handled as footer)
        if line.startswith("*Generated by"):
            i += 1
            continue
        if not line.strip():
            i += 1
            continue
        if line.strip() == "---":
            flow.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#cccccc"),
                                   spaceBefore=4, spaceAfter=6))
            i += 1
            continue
        if line.startswith("### "):
            flow.append(Paragraph(_inline(line[4:]), styles["H3"]))
            i += 1
            continue
        if line.startswith("## "):
            flow.append(Paragraph(_inline(line[3:]), styles["H2"]))
            i += 1
            continue
        if line.startswith("# "):
            flow.append(Paragraph(_inline(line[2:]), styles["H1"]))
            i += 1
            continue
        if line.lstrip().startswith("|") or line.lstrip().startswith("-") and "|" in line:
            # Table: collect consecutive pipe rows
            tbl = []
            while i < len(lines) and lines[i].strip().lstrip().startswith("|"):
                raw = lines[i].strip().strip("|")
                cells = [c.strip() for c in raw.split("|")]
                tbl.append(cells)
                i += 1
            # drop separator row (---|---)
            if tbl and all(set(c) <= set("-: ") for c in tbl[1]) and len(tbl) >= 2:
                tbl = [tbl[0]] + tbl[2:]
            if not tbl:
                continue
            header = tbl[0]
            data = [[Paragraph(_inline(c), styles["CellH"]) for c in header]]
            for r in tbl[1:]:
                # pad/truncate to header width
                r = (r + [""] * (len(header) - len(r)))[:len(header)]
                data.append([Paragraph(_inline(c), styles["Cell"]) for c in r])
            t = Table(data, hAlign="LEFT", repeatRows=1)
            style = [
                ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bbbbbb")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
            # row shading by risk level
            for ri, r in enumerate(tbl[1:], start=1):
                rowtext = " ".join(r)
                bg = _row_level_bg(rowtext)
                if bg is not None:
                    style.append(("BACKGROUND", (0, ri), (-1, ri), bg))
                elif ri % 2 == 0:
                    style.append(("BACKGROUND", (0, ri), (-1, ri), ROW_ALT))
            t.setStyle(TableStyle(style))
            flow.append(t)
            flow.append(Spacer(1, 6))
            continue
        if re.match(r"^\s*[-*]\s+", line):
            # bullet list (collect consecutive)
            items = []
            while i < len(lines) and re.match(r"^\s*[-*]\s+", lines[i].rstrip()):
                item = re.sub(r"^\s*[-*]\s+", "", lines[i].rstrip())
                items.append(ListItem(Paragraph(_inline(item), styles["Body"]), leftIndent=10))
                i += 1
            flow.append(ListFlowable(items, bulletType="bullet", start="•", leftIndent=12))
            flow.append(Spacer(1, 4))
            continue
        flow.append(Paragraph(_inline(line), styles["Body"]))
        i += 1
    return flow


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input_md")
    ap.add_argument("output_pdf")
    ap.add_argument("--title", default="")
    ap.add_argument("--image", action="append", default=[],
                    help="Embed a diagram: 'Title:/path.png' (repeatable)")
    args = ap.parse_args()

    md = Path(args.input_md).read_text()
    styles = _styles()
    flow = md_to_flowables(md, styles, title=args.title)

    # Appendix: embedded diagrams
    if args.image:
        flow.append(PageBreak())
        flow.append(Paragraph("Appendix: Diagrams", styles["H2"]))
        flow.append(HRFlowable(width="100%", thickness=0.8, color=HEADER_BG,
                               spaceBefore=2, spaceAfter=8))
        from reportlab.lib.utils import ImageReader
        page_w = A4[0] - 32 * mm  # usable width
        for spec in args.image:
            if ":" not in spec:
                continue
            title_txt, path = spec.split(":", 1)
            p = Path(path.strip())
            if not p.exists():
                flow.append(Paragraph(f"[missing diagram: {title_txt}]", styles["Meta"]))
                continue
            try:
                iw, ih = ImageReader(str(p)).getSize()
                scale = page_w / iw
                img = RLImage(str(p), width=page_w, height=ih * scale)
                flow.append(Paragraph(title_txt, styles["H3"]))
                flow.append(img)
                flow.append(Paragraph(f"Figure: {title_txt}", styles["FigCap"]))
                flow.append(Spacer(1, 6))
            except Exception as e:
                flow.append(Paragraph(f"[error embedding {title_txt}: {e}]", styles["Meta"]))

    doc = SimpleDocTemplate(
        args.output_pdf, pagesize=A4,
        leftMargin=16 * mm, rightMargin=16 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title="MoiraiCore Threat & Risk Assessment", author="MoiraiCore Threat Engine",
    )
    cover = []
    cover.append(Paragraph("MoiraiCore — Threat & Risk Assessment", styles["H1"]))
    cover.append(Paragraph("Confidential · Generated by MoiraiCore Threat Engine", styles["Meta"]))
    cover.append(HRFlowable(width="100%", thickness=1, color=HEADER_BG, spaceBefore=4, spaceAfter=8))
    doc.build(cover + flow)
    print(f"wrote {args.output_pdf}")


if __name__ == "__main__":
    raise SystemExit(main())

